char* remove_trailing_slashes(char* str);
struct ext2_dir_entry* get_prev_entry();
unsigned char* read_disk(char* path);
int absolute_path(char* path);
struct ext2_super_block* super_block();
struct ext2_group_desc* group_desc();
struct ext2_inode* inode_table();
unsigned char* block_bitmap();
unsigned char* inode_bitmap();
struct ext2_dir_entry* find_in_dir(struct ext2_inode *dir, char* name);
char* get_path(char* path);
char* get_filename(char* path);
struct ext2_inode* get_inode_from_no(int no);
int inode_is_set(int bit);
int get_rec_len(int x);
int allocate(unsigned char* bmp, int reversed, int size);
int allocate_inode();
void init_inode(struct ext2_inode* inode);
void set_inode(int bit);
void reset_inode(int bit);
void set_block(int bit);
void reset_block(int bit);
void set_all_blocks(struct ext2_inode* inode);
void reset_all_blocks(struct ext2_inode* inode);
int block_is_set(int bit);
int blocks_overwritten(struct ext2_inode* inode);
int allocate_block();
int is_directory(struct ext2_inode* inode);
struct ext2_dir_entry* last_entry(struct ext2_dir_entry *dir);
struct ext2_dir_entry* find_space(int block, char* filename, int fnamelen);
struct ext2_dir_entry* search_directory(struct ext2_inode* inode, char* name);
struct ext2_dir_entry* dir_insert(struct ext2_inode* parent, int inode, char* name, unsigned int type);
int check_path_exists(char* filepath);
struct ext2_dir_entry* search_and_restore(struct ext2_inode* parent, char* name);
int create_indirect_block(struct ext2_inode* inode, int block);
int add_block_to_inode(struct ext2_inode* inode, int block_no);
int inode_write(struct ext2_inode* inode, char* data, int len);
int get_free_bits_count(unsigned char* bmp, int size);
void delete(struct ext2_inode* parent, char* name, int name_length);